
package itson.org.ghosttracks.utilerias;

import itson.org.ghosttracks.controladores.Navegador;

/**
 *
 * @author oliro
 */
public class pnlMenuLateralAdmin extends javax.swing.JPanel {

    private final Navegador navegador;
    
    public pnlMenuLateralAdmin(Navegador nav) {
        this.navegador = nav;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMenu1 = new javax.swing.JLabel();
        btnVentas = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnArticulos = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        lblAdminnistracion = new javax.swing.JLabel();
        btnInventario = new java.awt.Label();

        setBackground(new java.awt.Color(230, 94, 7));

        lblMenu1.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblMenu1.setText("Menú principal");

        btnVentas.setBackground(new java.awt.Color(230, 94, 7));
        btnVentas.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.setBorder(null);
        btnVentas.setPreferredSize(new java.awt.Dimension(250, 40));
        btnVentas.addActionListener(this::btnVentasActionPerformed);

        btnInicio.setBackground(new java.awt.Color(230, 94, 7));
        btnInicio.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setBorder(null);
        btnInicio.setPreferredSize(new java.awt.Dimension(250, 40));

        btnArticulos.setBackground(new java.awt.Color(230, 94, 7));
        btnArticulos.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        btnArticulos.setText("Articulos");
        btnArticulos.setBorder(null);
        btnArticulos.setPreferredSize(new java.awt.Dimension(250, 40));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ghostracksLogo.png"))); // NOI18N

        btnCerrarSesion.setBackground(new java.awt.Color(230, 94, 7));
        btnCerrarSesion.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        btnCerrarSesion.setText("Cerrar sesón");
        btnCerrarSesion.setActionCommand("Cerrar sesión");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setPreferredSize(new java.awt.Dimension(200, 30));
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

        lblAdminnistracion.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblAdminnistracion.setText("Administracion");

        btnInventario.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(204, 204, 204));
        btnInventario.setText("Inventario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(lblMenu1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAdminnistracion))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblMenu1)
                .addGap(25, 25, 25)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lblAdminnistracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        navegador.irVentasAdmin();
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        navegador.cerrarSesion();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArticulos;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnInicio;
    private java.awt.Label btnInventario;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel lblAdminnistracion;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMenu1;
    // End of variables declaration//GEN-END:variables
}
