/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.org.ghosttracks.utilerias;

import itson.org.ghosttracks.controladores.ControlVentaEnLinea;
import itson.org.ghosttracks.dtos.CarritoDTO;
import itson.org.ghosttracks.dtos.ItemCarritoDTO;
import javax.swing.BoxLayout;

/**
 *
 * @author cinca
 */
public class pnlResumenPedido extends javax.swing.JPanel {
    private ControlVentaEnLinea control;
    /**
     * Creates new form pnlResumenPedido
     */
    public pnlResumenPedido() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTotales = new javax.swing.JPanel();
        lblTituloSubtotal = new javax.swing.JLabel();
        lblTituloTax = new javax.swing.JLabel();
        lblTituloTotal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblSubtotal = new javax.swing.JLabel();
        lblTax = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnContinuar = new itson.org.ghosttracks.utilerias.BotonRedondeado();
        btnEliminarCarrito = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlResumenProducto1 = new itson.org.ghosttracks.utilerias.pnlResumenProducto();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlContenedprProd = new javax.swing.JPanel();

        setBackground(new java.awt.Color(237, 229, 222));
        setPreferredSize(new java.awt.Dimension(348, 680));

        pnlTotales.setBackground(new java.awt.Color(153, 153, 153));
        pnlTotales.setForeground(new java.awt.Color(153, 153, 153));
        pnlTotales.setMinimumSize(new java.awt.Dimension(336, 173));

        lblTituloSubtotal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTituloSubtotal.setForeground(new java.awt.Color(51, 51, 51));
        lblTituloSubtotal.setText("Subtotal:");

        lblTituloTax.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTituloTax.setForeground(new java.awt.Color(51, 51, 51));
        lblTituloTax.setText("Tax (16%):");

        lblTituloTotal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTituloTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloTotal.setText("Total:");

        lblSubtotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSubtotal.setForeground(new java.awt.Color(51, 51, 51));
        lblSubtotal.setText("$0");

        lblTax.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTax.setForeground(new java.awt.Color(51, 51, 51));
        lblTax.setText("$0");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTotal.setText("$0");

        btnContinuar.setBackground(new java.awt.Color(204, 51, 0));
        btnContinuar.setText("Continuar");
        btnContinuar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnlTotalesLayout = new javax.swing.GroupLayout(pnlTotales);
        pnlTotales.setLayout(pnlTotalesLayout);
        pnlTotalesLayout.setHorizontalGroup(
            pnlTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(pnlTotalesLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTotalesLayout.createSequentialGroup()
                        .addComponent(lblTituloSubtotal)
                        .addGap(215, 215, 215)
                        .addComponent(lblSubtotal))
                    .addGroup(pnlTotalesLayout.createSequentialGroup()
                        .addComponent(lblTituloTax)
                        .addGap(195, 195, 195)
                        .addComponent(lblTax))
                    .addGroup(pnlTotalesLayout.createSequentialGroup()
                        .addComponent(lblTituloTotal)
                        .addGap(241, 241, 241)
                        .addComponent(lblTotal))))
            .addGroup(pnlTotalesLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlTotalesLayout.setVerticalGroup(
            pnlTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalesLayout.createSequentialGroup()
                .addGroup(pnlTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloSubtotal)
                    .addGroup(pnlTotalesLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblSubtotal)))
                .addGap(18, 18, 18)
                .addGroup(pnlTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloTax)
                    .addGroup(pnlTotalesLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblTax)))
                .addGap(16, 16, 16)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(pnlTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloTotal)
                    .addGroup(pnlTotalesLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblTotal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        btnEliminarCarrito.setBackground(new java.awt.Color(181, 181, 181));
        btnEliminarCarrito.setForeground(new java.awt.Color(204, 0, 0));
        btnEliminarCarrito.setText("Eliminar carrito");
        btnEliminarCarrito.setBorder(null);
        btnEliminarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCarritoActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\cinca\\Documents\\carro 1.png")); // NOI18N

        jPanel1.setBackground(new java.awt.Color(181, 181, 181));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Resumen");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlResumenProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(pnlResumenProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(434, Short.MAX_VALUE))
        );

        pnlContenedprProd.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlContenedprProdLayout = new javax.swing.GroupLayout(pnlContenedprProd);
        pnlContenedprProd.setLayout(pnlContenedprProdLayout);
        pnlContenedprProdLayout.setHorizontalGroup(
            pnlContenedprProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );
        pnlContenedprProdLayout.setVerticalGroup(
            pnlContenedprProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnlContenedprProd);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlTotales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEliminarCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(61, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCarritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarCarritoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private itson.org.ghosttracks.utilerias.BotonRedondeado btnContinuar;
    private javax.swing.JButton btnEliminarCarrito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTax;
    private javax.swing.JLabel lblTituloSubtotal;
    private javax.swing.JLabel lblTituloTax;
    private javax.swing.JLabel lblTituloTotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlContenedprProd;
    private itson.org.ghosttracks.utilerias.pnlResumenProducto pnlResumenProducto1;
    private javax.swing.JPanel pnlTotales;
    // End of variables declaration//GEN-END:variables
    
public void cargarProductos(CarritoDTO carrito) {
        jPanel1.removeAll();
        
        for(ItemCarritoDTO item: carrito.getProductos()){
            pnlResumenProducto pnl = new pnlResumenProducto();
            
            item.calcularSubtotal();
            pnl.enviarDatos(item);
            

            pnlContenedprProd.add(pnl);
        }
        pnlContenedprProd.revalidate();
        pnlContenedprProd.repaint();
   }


}
