/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.org.ghosttracks.presentacion.gestionProductos;

import itson.org.ghosttracks.controladores.Control;
import itson.org.ghosttracks.dtos.CatalogoProductosDTO;
import itson.org.ghosttracks.dtos.FiltroProductoDTO;
import itson.org.ghosttracks.dtos.GeneroDTO;
import itson.org.ghosttracks.dtos.ProductoDTO;
import itson.org.ghosttracks.dtos.TipoDTO;
import itson.org.ghosttracks.negocio.objetosNegocio.Excepciones.NegocioException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cinca
 */
public class PantallaCatalogo extends javax.swing.JPanel {
    private final Control controlador;
    ProductoDTO producto;
    
    /**
     * Creates new form pantallaCatalogo
     */
    public PantallaCatalogo(Control ctrl) {
        initComponents();
        this.controlador = ctrl;
        
        try {
            llenarTablaTodos();
        } catch (Exception ex) {
            controlador.mostrarMensajeErrorProductoNoEncontrado();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedorCatalogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new itson.org.ghosttracks.utilerias.BotonRedondeado();
        btnImprimirReporte = new itson.org.ghosttracks.utilerias.BotonRedondeado();
        btnAgregarProducto = new itson.org.ghosttracks.utilerias.BotonRedondeado();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();

        setBackground(new java.awt.Color(237, 229, 222));
        setPreferredSize(new java.awt.Dimension(1100, 675));

        pnlContenedorCatalogo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Buscar producto (Nombre, artista, tipo o genero)");

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setText("");
        txtBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnBuscar.setBackground(new java.awt.Color(204, 51, 0));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnImprimirReporte.setBackground(new java.awt.Color(204, 51, 0));
        btnImprimirReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimirReporte.setText("Generar reporte");
        btnImprimirReporte.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnImprimirReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirReporteActionPerformed(evt);
            }
        });

        btnAgregarProducto.setBackground(new java.awt.Color(204, 51, 0));
        btnAgregarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProducto.setText("+ Agregar producto nuevo");
        btnAgregarProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        tblProductos.setBackground(new java.awt.Color(255, 255, 255));
        tblProductos.setForeground(new java.awt.Color(0, 0, 0));
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Genero", "Artista", "Tipo", "Stock", "Seleccionar"
            }
        ));
        tblProductos.setGridColor(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(tblProductos);

        javax.swing.GroupLayout pnlContenedorCatalogoLayout = new javax.swing.GroupLayout(pnlContenedorCatalogo);
        pnlContenedorCatalogo.setLayout(pnlContenedorCatalogoLayout);
        pnlContenedorCatalogoLayout.setHorizontalGroup(
            pnlContenedorCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorCatalogoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlContenedorCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(pnlContenedorCatalogoLayout.createSequentialGroup()
                        .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnImprimirReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContenedorCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnlContenedorCatalogoLayout.createSequentialGroup()
                            .addComponent(txtBuscar)
                            .addGap(18, 18, 18)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlContenedorCatalogoLayout.setVerticalGroup(
            pnlContenedorCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorCatalogoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContenedorCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlContenedorCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimirReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(pnlContenedorCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(pnlContenedorCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            FiltroProductoDTO filtro = new FiltroProductoDTO();
            
            filtro.setNombre(txtBuscar.getText().trim());
            filtro.setArtista(txtBuscar.getText().trim());
            GeneroDTO genero = new GeneroDTO();
            genero.setNombreGenero(txtBuscar.getText().trim());
            filtro.setGenero(genero);
            TipoDTO tipo = new TipoDTO();
            tipo.setNombreTipo(txtBuscar.getText().trim());
            filtro.setTipo(tipo);
            
            
            List<CatalogoProductosDTO> productos = controlador.listarProductos(filtro);
            llenarTabla(productos);
            if(productos == null || productos.isEmpty()){
                controlador.mostrarMensajeErrorProductoNoEncontrado();
            }
           
        } catch (Exception e) {
            controlador.mostrarMensaje("Error al buscar productos", true);
    }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnImprimirReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirReporteActionPerformed
        try {
            // TODO add your handling code here:
            controlador.generarReporteProductos();
        } catch (NegocioException ex) {
            controlador.mostrarMensaje("No se pudo generar el reporte", true);
        
        }
        
    }//GEN-LAST:event_btnImprimirReporteActionPerformed

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
       controlador.mostrarPantallaFormularioProducto(producto);
    }//GEN-LAST:event_btnAgregarProductoActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private itson.org.ghosttracks.utilerias.BotonRedondeado btnAgregarProducto;
    private itson.org.ghosttracks.utilerias.BotonRedondeado btnBuscar;
    private itson.org.ghosttracks.utilerias.BotonRedondeado btnImprimirReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlContenedorCatalogo;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
    
    
    private void llenarTabla(List<CatalogoProductosDTO> productos) {
        DefaultTableModel tabla = (DefaultTableModel) tblProductos.getModel();
        tabla.setRowCount(0);
        for(CatalogoProductosDTO producto: productos) {
           Object[] fila = { 
               producto.getIdProducto(),
               producto.getNombre(),
               producto.getGenero().getNombreGenero(),
               producto.getArtista(),
               producto.getTipo().getNombreTipo(),
               producto.getStock(),
               "Seleccionar"
           }; 
           tabla.addRow(fila);
        }
        
        tblProductos.getColumnModel().getColumn(6);
        tblProductos.getColumnModel().getColumn(6);
    }
    
    private void llenarTablaTodos() {
       try {
        FiltroProductoDTO filtro = new FiltroProductoDTO();
        List<CatalogoProductosDTO> productos=controlador.listarProductos(null);
        
        DefaultTableModel tabla = (DefaultTableModel) tblProductos.getModel();
        tabla.setRowCount(0);
        for(CatalogoProductosDTO producto: productos) {

            tabla.addRow(new Object[] { 
               producto.getIdProducto(),
               producto.getNombre(),
               producto.getGenero().getNombreGenero(),
               producto.getArtista(),
               producto.getTipo().getNombreTipo(),
               producto.getStock(),
               "Seleccionar"
           });  
        }
        
        tblProductos.getColumnModel().getColumn(6);
        tblProductos.getColumnModel().getColumn(6);
        
    } catch (Exception e) {
        controlador.mostrarMensaje("Error al cargar productos", true);
    }
   }
}
