
package itson.org.ghosttracks.presentacion.administrador;

import itson.org.ghosttracks.controladores.ControladorVentasAdmin;
import itson.org.ghosttracks.dtos.PedidoDTO;
import itson.org.ghosttracks.utilerias.pnlDetallesPedido;
import java.util.List;

/**
 *
 * @author oliro
 */
public class PantallaVentas extends javax.swing.JPanel {
    
    private final ControladorVentasAdmin control;
    private final pnlDetallesPedido panelDetalles;
    
    public PantallaVentas(ControladorVentasAdmin ctrl) {
        this.control = ctrl;
        initComponents();
        this.panelDetalles = pnlDetallesPedido1;
        control.llenarTablaPedidos(this);
        
        
       
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        btnContinuar = new javax.swing.JButton();
        pnlDetallesPedido1 = new itson.org.ghosttracks.utilerias.pnlDetallesPedido();

        setPreferredSize(new java.awt.Dimension(1100, 675));

        pnlPrincipal.setBackground(new java.awt.Color(237, 229, 222));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(1100, 675));

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Venta", "Cliente", "Piezas", "Importe", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPedidos);

        btnContinuar.setBackground(new java.awt.Color(204, 0, 0));
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(this::btnContinuarActionPerformed);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContinuar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDetallesPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnContinuar)
                .addContainerGap(347, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlDetallesPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        control.procesarPedido();
    }//GEN-LAST:event_btnContinuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JScrollPane jScrollPane1;
    private itson.org.ghosttracks.utilerias.pnlDetallesPedido pnlDetallesPedido1;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTable tblPedidos;
    // End of variables declaration//GEN-END:variables

    public void llenarTabla(List<PedidoDTO> pedidos) {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblPedidos.getModel();
        modelo.setRowCount(0);

        for (PedidoDTO pedido : pedidos) {
            Object[] fila = new Object[5]; 

            fila[0] = pedido.getIdPedido(); 
            fila[1] = pedido.getIdCliente(); 
            fila[2] = "-";
            fila[3] = String.format("$%.2f", pedido.getTotal());
            fila[4] = pedido.getEstado() != null ? pedido.getEstado().name() : "Sin estado";

            modelo.addRow(fila);
        }
    }
}
