
package itson.org.ghosttracks.presentacion.cliente;

import itson.org.ghosttracks.controladores.ControlVentaEnLinea;
import itson.org.ghosttracks.dtos.DatosPagoDTO;
import itson.org.ghosttracks.presentacion.cliente.metodosDePago.PanelMetodoPagoTarjetaDebito;
import itson.org.ghosttracks.presentacion.cliente.metodosDePago.PanelSeleccionMetodoPago;
import itson.org.ghosttracks.utilerias.pnlResumenPedido;
import java.awt.CardLayout;
import java.util.List;

/**
 *
 * @author oliro
 */
public class PantallaSeleccionMetodoDePago extends javax.swing.JPanel {

    private ControlVentaEnLinea control;
    private CardLayout cardLayout;
    private pnlResumenPedido panelResumen;
    
    public PantallaSeleccionMetodoDePago(ControlVentaEnLinea ctrl) {
        this.control = ctrl;
        
        initComponents();
        
        this.panelResumen = new pnlResumenPedido();
        
        cardLayout = new CardLayout();
        panelContenido.setLayout(cardLayout);
        
        // Pasamos 'this' para que los paneles puedan avisar cuando cambiar
        PanelSeleccionMetodoPago seleccion = new PanelSeleccionMetodoPago(this);
        PanelMetodoPagoTarjetaDebito debito = new PanelMetodoPagoTarjetaDebito(this);
        
        panelContenido.add(seleccion, "PAGO_SELECCION");
        panelContenido.add(debito, "PAGO_TARJETA");
        
        cardLayout.show(panelContenido, "PAGO_SELECCION");
        control.llenarResumenPedido(panelResumen);
        
    }
    
    public void setDatosPago(DatosPagoDTO dto) {
        control.agregarMetodoPago(dto);
        control.procesarPedido();
        control.mostrarSeguimientoPedido();
        
    }
    
    public void cambiarPantalla(String nombrePantalla) {
        cardLayout.show(panelContenido, nombrePantalla);
    }
    
    public void mostrarMensaje(String mensaje, boolean esError) {
        control.mostrarMensaje(mensaje, esError);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlResumenPedido1 = new itson.org.ghosttracks.utilerias.pnlResumenPedido();
        panelContenido = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1100, 675));

        pnlPrincipal.setBackground(new java.awt.Color(237, 229, 222));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(1100, 675));

        panelContenido.setOpaque(false);
        panelContenido.setPreferredSize(new java.awt.Dimension(700, 675));

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlResumenPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlResumenPedido1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                    .addComponent(panelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel pnlPrincipal;
    private itson.org.ghosttracks.utilerias.pnlResumenPedido pnlResumenPedido1;
    // End of variables declaration//GEN-END:variables
}
