
package itson.org.ghosttracks.presentacion.cliente;

import itson.org.ghosttracks.controladores.ControlVentaEnLinea;
import itson.org.ghosttracks.dtos.DireccionEntregaDTO;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.JTextField;

/**
 *
 * @author oliro
 */
public class PantallaFormularioEntrega extends javax.swing.JPanel {

    private final ControlVentaEnLinea control;
    
    private final String PH_NOMBRES = "Nombre(s)";
    private final String PH_APELLIDOS = "Apellido(s)";
    private final String PH_CALLE = "Calle";
    private final String PH_NUMERO = "Numero";
    private final String PH_CP = "Codigo Postal";
    private final String PH_CIUDAD = "Ciudad";
    private final String PH_ESTADO = "Estado";
    
    public PantallaFormularioEntrega(ControlVentaEnLinea ctrl) {
        this.control = ctrl;
        initComponents();
        configurarPlaceholders();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlContenedor = new javax.swing.JPanel();
        pnlFormulario = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        jLabel1 = new javax.swing.JLabel();
        txtNombres = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        txtApellidos = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        txtCodigoPostal = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        txtCalle = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        txtCiudad = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        txtEstado = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        btnGuardar = new itson.org.ghosttracks.utilerias.BotonRedondeado();
        txtNumero = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();

        pnlPrincipal.setBackground(new java.awt.Color(51, 51, 51));
        pnlPrincipal.setMinimumSize(new java.awt.Dimension(1400, 800));

        pnlContenedor.setBackground(new java.awt.Color(237, 229, 222));
        pnlContenedor.setMinimumSize(new java.awt.Dimension(752, 690));
        pnlContenedor.setPreferredSize(new java.awt.Dimension(1100, 675));

        pnlFormulario.setBackground(new java.awt.Color(204, 204, 204));
        pnlFormulario.setMinimumSize(new java.awt.Dimension(698, 294));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Entrega");

        txtNombres.setBackground(new java.awt.Color(255, 255, 255));
        txtNombres.setText("Nombre(s)");

        txtApellidos.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidos.setText("Apellido(s)");

        txtCodigoPostal.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoPostal.setText("Codigo Postal");

        txtCalle.setBackground(new java.awt.Color(255, 255, 255));
        txtCalle.setText("Calle");

        txtCiudad.setBackground(new java.awt.Color(255, 255, 255));
        txtCiudad.setText("Ciudad");

        txtEstado.setBackground(new java.awt.Color(255, 255, 255));
        txtEstado.setText("Estado");

        btnGuardar.setBackground(new java.awt.Color(204, 51, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        txtNumero.setBackground(new java.awt.Color(255, 255, 255));
        txtNumero.setText("Numero");

        javax.swing.GroupLayout pnlFormularioLayout = new javax.swing.GroupLayout(pnlFormulario);
        pnlFormulario.setLayout(pnlFormularioLayout);
        pnlFormularioLayout.setHorizontalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlFormularioLayout.createSequentialGroup()
                            .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2))
                        .addGroup(pnlFormularioLayout.createSequentialGroup()
                            .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCalle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombres, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlFormularioLayout.createSequentialGroup()
                                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormularioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291))
        );
        pnlFormularioLayout.setVerticalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlContenedorLayout = new javax.swing.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenedorLayout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(pnlFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pnlFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String nombres = txtNombres.getText().trim();
        String apellidos = txtApellidos.getText().trim();
        String calle = txtCalle.getText().trim();
        String numero = txtNumero.getText().trim();
        String cp = txtCodigoPostal.getText().trim();
        String ciudad = txtCiudad.getText().trim();
        String estado = txtEstado.getText().trim();
        
        if (validarFormulario(nombres, apellidos, calle, numero, cp, ciudad, estado)) {
            enviarDatos(nombres, apellidos, calle, numero, cp, ciudad, estado);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private boolean validarFormulario(String nombres, String apellidos, String calle, String numero, String cp, String ciudad, String estado) {
        // Validar que ningún campo esté vacío o con el placeholder por defecto
        if (nombres.equals(PH_NOMBRES) || apellidos.equals(PH_APELLIDOS) || 
            calle.equals(PH_CALLE) || numero.equals(PH_NUMERO) || 
            cp.equals(PH_CP) || ciudad.equals(PH_CIUDAD) || estado.equals(PH_ESTADO)) {
            
            control.mostrarMensaje("Todos los campos son obligatorios. Por favor, llena la información faltante.", false);
            return false;
        }

        // Regex: Solo letras y espacios para nombres/apellidos/ciudad/estado
        String regexLetras = "^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$";
        
        if (!nombres.matches(regexLetras) || !apellidos.matches(regexLetras)) {
            control.mostrarMensaje("Los nombres y apellidos solo deben contener letras.", false);
            return false;
        }

        if (!ciudad.matches(regexLetras) || !estado.matches(regexLetras)) {
            control.mostrarMensaje("La ciudad y el estado solo deben contener letras.", false);
            return false;
        }

        // Regex: Código Postal de exactamente 5 dígitos
        if (!cp.matches("^\\d{5}$")) {
            control.mostrarMensaje("El Código Postal debe contener exactamente 5 dígitos numéricos.", false);
            return false;
        }
        
        return true;
    }
    
    private void configurarPlaceholders() {
        agregarPlaceholder(txtNombres, PH_NOMBRES);
        agregarPlaceholder(txtApellidos, PH_APELLIDOS);
        agregarPlaceholder(txtCalle, PH_CALLE);
        agregarPlaceholder(txtNumero, PH_NUMERO);
        agregarPlaceholder(txtCodigoPostal, PH_CP);
        agregarPlaceholder(txtCiudad, PH_CIUDAD);
        agregarPlaceholder(txtEstado, PH_ESTADO);
    }
    
    private void agregarPlaceholder(JTextField campo, String placeholder) {
        campo.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (campo.getText().equals(placeholder)) {
                    campo.setText("");
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if (campo.getText().isEmpty()) {
                    campo.setText(placeholder);
                }
            }
        });
    }

    private void enviarDatos(String nombres, String apellidos, String calle, String numero, String cp, String ciudad, String estado) {
        DireccionEntregaDTO dto = new DireccionEntregaDTO();
        dto.setNombre(nombres);
        dto.setApellido(apellidos);
        dto.setCalle(calle);
        dto.setNumero(numero);
        dto.setCodigoPostal(cp);
        dto.setCiudad(ciudad);
        dto.setEstado(estado);
        
        control.agregarDireccionPedido(dto);
        control.procesarPedidoMetodoPago();
        control.mostrarMensaje("Dirección guardada con éxito.", false);
         
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private itson.org.ghosttracks.utilerias.BotonRedondeado btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlContenedor;
    private itson.org.ghosttracks.utilerias.PanelRedondeado pnlFormulario;
    private javax.swing.JPanel pnlPrincipal;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtApellidos;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtCalle;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtCiudad;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtCodigoPostal;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtEstado;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtNombres;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtNumero;
    // End of variables declaration//GEN-END:variables
}
