/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.org.ghosttracks.presentacion.cliente;

import java.util.List;

import itson.org.ghosttracks.controladores.ControlVentaEnLinea;
import itson.org.ghosttracks.dtos.ItemCarritoDTO;
import itson.org.ghosttracks.dtos.PedidoDTO;
import itson.org.ghosttracks.enums.TipoPago;

/**
 *
 * @author cinca
 */
public class PantallaPedidosProceso extends javax.swing.JPanel {
    private ControlVentaEnLinea control;
    
    /**
     * Creates new form PantallaPedidosProceso
     */
    public PantallaPedidosProceso(ControlVentaEnLinea ctrl) {
        this.control = ctrl;
        
        initComponents();
        
        
        this.control.obtenerPedidosCliente(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPedidos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(237, 229, 222));
        setPreferredSize(new java.awt.Dimension(1400, 800));

        tablaPedidos.setBackground(new java.awt.Color(204, 204, 204));
        tablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Productos", "Metodo de pago", "Direccion", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tablaPedidos);

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Pedidos realizados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(234, 234, 234))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void llenarTablaPedidos(List<PedidoDTO> pedidos) {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaPedidos.getModel();
        modelo.setRowCount(0);
        
        
        if (pedidos == null || pedidos.isEmpty()) {
            Object[] filaVacia = {"Sin datos", "N/A", "N/A", "N/A"};
            modelo.addRow(filaVacia);
            return;
        }
        
        for (PedidoDTO pedido : pedidos) {
            try {
                StringBuilder productosNombres = new StringBuilder();
                
                if (pedido.getProductos() != null && !pedido.getProductos().isEmpty()) {
                    for (int i = 0; i < pedido.getProductos().size(); i++) {
                        ItemCarritoDTO item = pedido.getProductos().get(i);
                        
                        if (item != null && item.getProductoSeleccionado() != null) {
                            productosNombres.append(item.getProductoSeleccionado().getNombre());
                            if (i < pedido.getProductos().size() - 1) {
                                productosNombres.append(", ");
                            }
                        }
                    }
                } else {
                    productosNombres.append("Pedido").append(pedido.getIdPedido());
                }
                
                String metodoPago = "no disp";
                if (pedido.getDatosPago() != null && pedido.getDatosPago().getTipoPago() != null) {
                    TipoPago tipo = pedido.getDatosPago().getTipoPago();
                    
                    metodoPago = tipo.name();
                    
                    
       
                }

                String direccion = "no disp";
                if (pedido.getDireccionEntrega() != null && pedido.getDireccionEntrega().getCalle() != null) {
                    direccion = pedido.getDireccionEntrega().getCalle();
                }

                String estado = "no disp";
                if (pedido.getEstado() != null) {
                    estado = pedido.getEstado().name();
                }

                Object[] fila = new Object[4];
                fila[0] = productosNombres.toString();
                fila[1] = metodoPago;
                fila[2] = direccion;
                fila[3] = estado;
                
                modelo.addRow(fila);
              
            } catch (Exception ex) {
                System.out.println("Error al agregar pedido a la tabla: " + ex.getMessage());
            }
        }
        
        tablaPedidos.repaint();
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPedidos;
    // End of variables declaration//GEN-END:variables
}
