
package itson.org.ghosttracks.presentacion.cliente;

import itson.org.ghosttracks.controladores.ControlVentaEnLinea;
import itson.org.ghosttracks.dtos.CarritoDTO;
import itson.org.ghosttracks.dtos.ItemCarritoDTO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cinca
 */
public class PantallaCarrito extends javax.swing.JPanel {

    private final ControlVentaEnLinea control;
    
    public PantallaCarrito(ControlVentaEnLinea ctrl) {
        this.control = ctrl;
        initComponents();
        control.llenarTablaCarrito(this);
        
        tblCarrito.setRowHeight(40);
        tblCarrito.getTableHeader().setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
        tblCarrito.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 14));
        
        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        tblCarrito.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tblCarrito.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlContenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonRedondeado1 = new itson.org.ghosttracks.utilerias.BotonRedondeado();
        jLabel3 = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCarrito = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();

        pnlPrincipal.setPreferredSize(new java.awt.Dimension(1100, 675));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContenedor.setBackground(new java.awt.Color(237, 229, 222));
        pnlContenedor.setPreferredSize(new java.awt.Dimension(1100, 692));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Tu carrito");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carro 1.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        botonRedondeado1.setBackground(new java.awt.Color(204, 51, 0));
        botonRedondeado1.setText("Continuar");
        botonRedondeado1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botonRedondeado1.addActionListener(this::botonRedondeado1ActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Impuestos y costos de envio seran calculados  al final de la compra.");

        lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl.setText("Subtotal");

        lblSubtotal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSubtotal.setText("$0.0");
        lblSubtotal.setPreferredSize(new java.awt.Dimension(175, 22));

        tblCarrito.setBackground(new java.awt.Color(204, 204, 204));
        tblCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "#", "Producto", "Cantidad", "Subtotal", "Eliminar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCarrito.setPreferredSize(new java.awt.Dimension(1070, 400));
        tblCarrito.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblCarrito);
        if (tblCarrito.getColumnModel().getColumnCount() > 0) {
            tblCarrito.getColumnModel().getColumn(0).setMinWidth(0);
            tblCarrito.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblCarrito.getColumnModel().getColumn(0).setMaxWidth(0);
            tblCarrito.getColumnModel().getColumn(1).setMinWidth(100);
            tblCarrito.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblCarrito.getColumnModel().getColumn(1).setMaxWidth(100);
            tblCarrito.getColumnModel().getColumn(2).setResizable(false);
            tblCarrito.getColumnModel().getColumn(3).setMinWidth(200);
            tblCarrito.getColumnModel().getColumn(3).setPreferredWidth(200);
            tblCarrito.getColumnModel().getColumn(3).setMaxWidth(200);
            tblCarrito.getColumnModel().getColumn(4).setMinWidth(200);
            tblCarrito.getColumnModel().getColumn(4).setPreferredWidth(200);
            tblCarrito.getColumnModel().getColumn(4).setMaxWidth(200);
            tblCarrito.getColumnModel().getColumn(5).setMinWidth(100);
            tblCarrito.getColumnModel().getColumn(5).setPreferredWidth(100);
            tblCarrito.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        javax.swing.GroupLayout pnlContenedorLayout = new javax.swing.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(pnlContenedorLayout.createSequentialGroup()
                        .addComponent(lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlContenedorLayout.createSequentialGroup()
                            .addComponent(btnEliminar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonRedondeado1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlContenedorLayout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel1))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorLayout.createSequentialGroup()
                .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(pnlContenedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl)
                    .addComponent(lblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRedondeado1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pnlPrincipal.add(pnlContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonRedondeado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRedondeado1ActionPerformed
        control.comenzarProcesoPedido();
    }//GEN-LAST:event_botonRedondeado1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    public void llenarTabla(CarritoDTO carrito) {
        List<ItemCarritoDTO> productos = carrito.getProductos();
        DefaultTableModel modelo = (DefaultTableModel) tblCarrito.getModel();
        modelo.setRowCount(0);

        int contador = 1;
        for (ItemCarritoDTO item : productos) {
            Object[] fila = new Object[6];

            fila[0] = contador++;                           
            fila[1] = item.getProductoSeleccionado().getIdProducto(); 
            fila[2] = item.getProductoSeleccionado().getNombre();     
            fila[3] = item.getCantidad();                             
            fila[4] = String.format("$%.2f", item.getSubtotal());   
            fila[5] = "Eliminar";                                     

            modelo.addRow(fila);
        }

        tblCarrito.getColumnModel().getColumn(1).setMinWidth(0);
        tblCarrito.getColumnModel().getColumn(1).setPreferredWidth(0);
        tblCarrito.getColumnModel().getColumn(1).setMaxWidth(0);

        tblCarrito.getColumnModel().getColumn(5).setCellRenderer(new ButtonRenderer());
        tblCarrito.getColumnModel().getColumn(5).setCellEditor(new ButtonEditor(new javax.swing.JCheckBox()));

        lblSubtotal.setText(String.format("$%.2f", carrito.getTotal()));
        
    }
    
    class ButtonRenderer extends javax.swing.JButton implements javax.swing.table.TableCellRenderer {
        public ButtonRenderer() { 
            setOpaque(true);
           
            setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        }

        @Override
        public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            setText("Eliminar");
            setBackground(new java.awt.Color(204, 51, 0)); 
            setForeground(java.awt.Color.WHITE);
            setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 12));
            return this;
        }
    }

    class ButtonEditor extends javax.swing.DefaultCellEditor {
        protected javax.swing.JButton button;
        private String label;
        private boolean isPushed;

        public ButtonEditor(javax.swing.JCheckBox checkBox) {
            super(checkBox);
            button = new javax.swing.JButton();
            button.setOpaque(true);
            button.addActionListener(e -> fireEditingStopped());
        }

        @Override
        public java.awt.Component getTableCellEditorComponent(javax.swing.JTable table, Object value,
                boolean isSelected, int row, int column) {
            label = (value == null) ? "Eliminar" : value.toString();
            button.setText(label);
            isPushed = true;
            return button;
        }

        @Override
        public Object getCellEditorValue() {
            if (isPushed) {
                int fila = tblCarrito.getSelectedRow();
                
                if (fila >= 0) {
                    Object value = tblCarrito.getValueAt(fila, 1); 

                    if (value instanceof Long) {
                        Long idProducto = (Long) value;
                        javax.swing.SwingUtilities.invokeLater(() -> {
                            control.eliminarProductoCarrito(idProducto);
                            control.llenarTablaCarrito(PantallaCarrito.this);
                        });
                    }
                }
            }
            isPushed = false;
            return label;
        }

        @Override
        public boolean stopCellEditing() {
            isPushed = false;
            return super.stopCellEditing();
        }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private itson.org.ghosttracks.utilerias.BotonRedondeado botonRedondeado1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTable tblCarrito;
    // End of variables declaration//GEN-END:variables
}
