
package itson.org.ghosttracks.presentacion.cliente.metodosDePago;

import itson.org.ghosttracks.presentacion.cliente.PantallaSeleccionMetodoDePago;

/**
 *
 * @author oliro
 */
public class PanelSeleccionMetodoPago extends javax.swing.JPanel {

    private PantallaSeleccionMetodoDePago principal;
    
    public PanelSeleccionMetodoPago(PantallaSeleccionMetodoDePago principal) {
        this.principal = principal;
        initComponents();
        configurarEventos();
    }

    private void configurarEventos() {
        btnContinuar19.addActionListener(e -> {
            if (rbtnTarjetaDebito2.isSelected()) {
                principal.cambiarPantalla("PAGO_TARJETA");
            } else if (rbtnMercadoPago2.isSelected()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Método no implementado aún.");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor seleccione un método.");
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelRedondeado19 = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        lblMetodoDePago19 = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        rbtnMercadoPago2 = new javax.swing.JRadioButton();
        rbtnTarjetaDebito2 = new javax.swing.JRadioButton();
        btnContinuar19 = new itson.org.ghosttracks.utilerias.BotonRedondeado();

        setOpaque(false);

        panelRedondeado19.setBackground(new java.awt.Color(217, 217, 217));
        panelRedondeado19.setPreferredSize(new java.awt.Dimension(700, 305));

        lblMetodoDePago19.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblMetodoDePago19.setText("Seleccione un método de pago");

        lblTitulo2.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        lblTitulo2.setText("Método de Pago");

        buttonGroup1.add(rbtnMercadoPago2);
        rbtnMercadoPago2.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        rbtnMercadoPago2.setText("Mercado Pago");
        rbtnMercadoPago2.setContentAreaFilled(false);
        rbtnMercadoPago2.addActionListener(this::rbtnMercadoPago2ActionPerformed);

        buttonGroup1.add(rbtnTarjetaDebito2);
        rbtnTarjetaDebito2.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        rbtnTarjetaDebito2.setText("Tarjeta de débito");
        rbtnTarjetaDebito2.setContentAreaFilled(false);

        btnContinuar19.setBackground(new java.awt.Color(230, 94, 7));
        btnContinuar19.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar19.setText("Continuar");
        btnContinuar19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnContinuar19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContinuar19.setHoverColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelRedondeado19Layout = new javax.swing.GroupLayout(panelRedondeado19);
        panelRedondeado19.setLayout(panelRedondeado19Layout);
        panelRedondeado19Layout.setHorizontalGroup(
            panelRedondeado19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado19Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelRedondeado19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMetodoDePago19)
                    .addComponent(rbtnTarjetaDebito2)
                    .addComponent(rbtnMercadoPago2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContinuar19, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(354, Short.MAX_VALUE))
        );
        panelRedondeado19Layout.setVerticalGroup(
            panelRedondeado19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado19Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitulo2)
                .addGap(15, 15, 15)
                .addComponent(lblMetodoDePago19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnTarjetaDebito2)
                .addGap(18, 18, 18)
                .addComponent(rbtnMercadoPago2)
                .addGap(64, 64, 64)
                .addComponent(btnContinuar19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelRedondeado19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelRedondeado19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnMercadoPago2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMercadoPago2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMercadoPago2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private itson.org.ghosttracks.utilerias.BotonRedondeado btnContinuar19;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblMetodoDePago19;
    private javax.swing.JLabel lblTitulo2;
    private itson.org.ghosttracks.utilerias.PanelRedondeado panelRedondeado19;
    private javax.swing.JRadioButton rbtnMercadoPago2;
    private javax.swing.JRadioButton rbtnTarjetaDebito2;
    // End of variables declaration//GEN-END:variables
}
