/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.org.ghosttracks.presentacion.cliente.metodosDePago;

import itson.org.ghosttracks.dtos.DatosPagoDTO;
import itson.org.ghosttracks.enums.TipoPago;
import itson.org.ghosttracks.presentacion.cliente.PantallaSeleccionMetodoDePago;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.JTextField;

/**
 *
 * @author cinca
 */
public class PanelMercadoPago extends javax.swing.JPanel {
    private PantallaSeleccionMetodoDePago principal;
    
    private final String PH_NUMERO = "Número de tarjeta";
    private final String PH_CVV = "CVV";
    private final String PH_FECHA = "Fecha Vencimiento";
    private final String PH_TITULAR = "Nombre del titular";
    
    /**
     * Creates new form PanelMercadoPago
     */
    public PanelMercadoPago(PantallaSeleccionMetodoDePago principal) {
        this.principal = principal;
        initComponents();
        configurarPlaceholders();
        configurarEventos();
    }

    private void agregarPlaceholder(JTextField campo, String placeholder) {
        campo.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (campo.getText().equals(placeholder)) {
                    campo.setText("");
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if (campo.getText().isEmpty()) {
                    campo.setText(placeholder);
                }
            }
        });
    }

    private void configurarPlaceholders() {
        agregarPlaceholder(txtNumeroTarjeta, PH_NUMERO);
        agregarPlaceholder(txtNumeroSeguridad, PH_CVV);
        agregarPlaceholder(txtFechaVencimiento, PH_FECHA);
        agregarPlaceholder(txtNombreTitular, PH_TITULAR);
    }
    
    private void configurarEventos() {
        // Botón Volver
        btnVolver.addActionListener(e -> {
            principal.cambiarPantalla("PAGO_SELECCION");
        });

        // Botón Continuar (Procesar el pago)
        btnContinuar.addActionListener(e -> {
            procesarFormulario();
        });
    }
    
    private void procesarFormulario() {
        String numero = txtNumeroTarjeta.getText().trim();
        String fecha = txtFechaVencimiento.getText().trim();
        String cvv = txtNumeroSeguridad.getText().trim();
        String titular = txtNombreTitular.getText().trim();

        if (validarDatos(numero, fecha, cvv, titular)) {
            enviarDatos(numero, fecha, cvv, titular);
            
            principal.cambiarPantalla("SEGUIMIENTO_PEDIDO");
        }
        
    }
    
    private boolean validarDatos(String num, String fec, String cvv, String tit) {
        // 1. Verificar vacíos o placeholders
        if (num.equals(PH_NUMERO) || fec.equals(PH_FECHA) || cvv.equals(PH_CVV) || tit.equals(PH_TITULAR)) {
            principal.mostrarMensaje("Todos los campos son obligatorios.", false);
            return false;
        }

        // 2. Regex Número de Tarjeta (16 dígitos)
        if (!num.matches("^\\d{16}$")) {
            principal.mostrarMensaje("El número de tarjeta debe tener 16 dígitos numéricos.", false);
            return false;
        }

        // 3. Regex Fecha Vencimiento (Formato MM/YY)
        if (!fec.matches("^(0[1-9]|1[0-2])\\/\\d{2}$")) {
            principal.mostrarMensaje("Formato de fecha inválido. Usa MM/YY (ej: 12/26).", false);
            return false;
        }

        // 4. Regex CVV (3 dígitos)
        if (!cvv.matches("^\\d{3}$")) {
            principal.mostrarMensaje("El CVV debe tener 3 dígitos.", false);
            return false;
        }

        // 5. Regex Titular (Solo letras)
        if (!tit.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$")) {
            principal.mostrarMensaje("El nombre del titular solo debe contener letras.", false);
            return false;
        }

        return true;
    }
    
    private void enviarDatos(String num, String fec, String cvv, String tit) {
        DatosPagoDTO datos = new DatosPagoDTO();
        datos.setTipoPago(TipoPago.MERCADO_PAGO);
        ;
        // datos.setFechaExpiracion(fec);
        datos.setCvv(cvv);
        datos.setTitularTarjeta(tit);

        principal.mostrarMensaje("Datos de pago validados correctamente.", false);
        principal.setDatosPago(datos);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSeleccionMetodoPago = new javax.swing.JLabel();
        lblMetodoDePago = new javax.swing.JLabel();
        txtNumeroTarjeta = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        txtNumeroSeguridad = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        txtNombreTitular = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        btnContinuar = new itson.org.ghosttracks.utilerias.BotonRedondeado();
        btnVolver = new javax.swing.JButton();
        txtFechaVencimiento = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();

        setBackground(new java.awt.Color(217, 217, 217));
        setMaximumSize(new java.awt.Dimension(700, 333));
        setPreferredSize(new java.awt.Dimension(700, 335));

        lblSeleccionMetodoPago.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        lblSeleccionMetodoPago.setText("Método de Pago");

        lblMetodoDePago.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblMetodoDePago.setText("MERCADO PAGO");

        txtNumeroTarjeta.setText("Numero de tarjeta");
        txtNumeroTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroTarjetaActionPerformed(evt);
            }
        });

        txtNumeroSeguridad.setText("CVV");

        txtNombreTitular.setText("Nombre del titular");
        txtNombreTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreTitularActionPerformed(evt);
            }
        });

        btnContinuar.setBackground(new java.awt.Color(230, 94, 7));
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("Continuar");
        btnContinuar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnContinuar.setHoverColor(new java.awt.Color(255, 255, 255));

        btnVolver.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(0, 0, 0));
        btnVolver.setText("Volver");
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);

        txtFechaVencimiento.setText("Fecha de vencimiento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNumeroSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtNumeroTarjeta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVolver)
                                .addGap(368, 368, 368)
                                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSeleccionMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMetodoDePago, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblSeleccionMetodoPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMetodoDePago)
                .addGap(18, 18, 18)
                .addComponent(txtNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(txtNombreTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreTitularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreTitularActionPerformed

    private void txtNumeroTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroTarjetaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private itson.org.ghosttracks.utilerias.BotonRedondeado btnContinuar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblMetodoDePago;
    private javax.swing.JLabel lblSeleccionMetodoPago;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtFechaVencimiento;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtNombreTitular;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtNumeroSeguridad;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtNumeroTarjeta;
    // End of variables declaration//GEN-END:variables
}
