 
package itson.org.ghosttracks.presentacion.cliente.metodosDePago;

import itson.org.ghosttracks.dtos.DatosPagoDTO;
import itson.org.ghosttracks.dtos.PedidoDTO;
import itson.org.ghosttracks.enums.TipoPago;
import itson.org.ghosttracks.presentacion.cliente.PantallaSeleccionMetodoDePago;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.JTextField;

/**
 *
 * @author oliro
 */
public class PanelMetodoPagoTarjetaDebito extends javax.swing.JPanel {
    
    private PantallaSeleccionMetodoDePago principal;
    
    private final String PH_NUMERO = "Número de tarjeta";
    private final String PH_CVV = "CVV";
    private final String PH_FECHA = "Fecha Vencimiento";
    private final String PH_TITULAR = "Nombre del titular";
    
    public PanelMetodoPagoTarjetaDebito(PantallaSeleccionMetodoDePago principal) {
        this.principal = principal;
        initComponents();
        configurarPlaceholders();
        configurarEventos();
    }

    private void agregarPlaceholder(JTextField campo, String placeholder) {
        campo.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (campo.getText().equals(placeholder)) {
                    campo.setText("");
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if (campo.getText().isEmpty()) {
                    campo.setText(placeholder);
                }
            }
        });
    }

    private void configurarPlaceholders() {
        agregarPlaceholder(txtNumeroTarjeta, PH_NUMERO);
        agregarPlaceholder(txtNumeroSeguridad, PH_CVV);
        agregarPlaceholder(txtFechaVencimiento, PH_FECHA);
        agregarPlaceholder(txtNombreTitular, PH_TITULAR);
    }
    
    private void configurarEventos() {
        // Botón Volver
        btnVolver.addActionListener(e -> {
            principal.cambiarPantalla("PAGO_SELECCION");
        });

        // Botón Continuar (Procesar el pago)
        btnContinuar.addActionListener(e -> {
            procesarFormulario();
        });
    }
    
    private void procesarFormulario() {
        String numero = txtNumeroTarjeta.getText().trim();
        String fecha = txtFechaVencimiento.getText().trim();
        String cvv = txtNumeroSeguridad.getText().trim();
        String titular = txtNombreTitular.getText().trim();

        if (validarDatos(numero, fecha, cvv, titular)) {
            enviarDatos(numero, fecha, cvv, titular);
        }
        
    }
    
    private boolean validarDatos(String num, String fec, String cvv, String tit) {
        // 1. Verificar vacíos o placeholders
        if (num.equals(PH_NUMERO) || fec.equals(PH_FECHA) || cvv.equals(PH_CVV) || tit.equals(PH_TITULAR)) {
            principal.mostrarMensaje("Todos los campos son obligatorios.", false);
            return false;
        }

        // 2. Regex Número de Tarjeta (16 dígitos)
        if (!num.matches("^\\d{16}$")) {
            principal.mostrarMensaje("El número de tarjeta debe tener 16 dígitos numéricos.", false);
            return false;
        }

        // 3. Regex Fecha Vencimiento (Formato MM/YY)
        if (!fec.matches("^(0[1-9]|1[0-2])\\/\\d{2}$")) {
            principal.mostrarMensaje("Formato de fecha inválido. Usa MM/YY (ej: 12/26).", false);
            return false;
        }

        // 4. Regex CVV (3 dígitos)
        if (!cvv.matches("^\\d{3}$")) {
            principal.mostrarMensaje("El CVV debe tener 3 dígitos.", false);
            return false;
        }

        // 5. Regex Titular (Solo letras)
        if (!tit.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$")) {
            principal.mostrarMensaje("El nombre del titular solo debe contener letras.", false);
            return false;
        }

        return true;
    }
    
    private void enviarDatos(String num, String fec, String cvv, String tit) {
        DatosPagoDTO datos = new DatosPagoDTO();
        datos.setTipoPago(TipoPago.STRIPE);

        principal.mostrarMensaje("Datos de pago validados correctamente.", false);
        principal.setDatosPago(datos);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        panelRedondeado = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        lblMetodoDePago = new javax.swing.JLabel();
        lblSeleccionMetodoPago = new javax.swing.JLabel();
        txtNumeroTarjeta = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        txtNumeroSeguridad = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        txtFechaVencimiento = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        txtNombreTitular = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        btnContinuar = new itson.org.ghosttracks.utilerias.BotonRedondeado();
        btnVolver = new javax.swing.JButton();

        setOpaque(false);

        pnlPrincipal.setBackground(new java.awt.Color(237, 229, 222));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(1100, 675));

        panelRedondeado.setBackground(new java.awt.Color(217, 217, 217));
        panelRedondeado.setPreferredSize(new java.awt.Dimension(700, 335));

        lblMetodoDePago.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblMetodoDePago.setText("Tarjeta de Débito");

        lblSeleccionMetodoPago.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        lblSeleccionMetodoPago.setText("Método de Pago");

        txtNumeroTarjeta.setText("Número de tarjeta");
        txtNumeroTarjeta.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        txtNumeroTarjeta.addActionListener(this::txtNumeroTarjetaActionPerformed);

        txtNumeroSeguridad.setText("CVV");
        txtNumeroSeguridad.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        txtNumeroSeguridad.setName("CVV"); // NOI18N
        txtNumeroSeguridad.addActionListener(this::txtNumeroSeguridadActionPerformed);

        txtFechaVencimiento.setText("Fecha Vencimiento");
        txtFechaVencimiento.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N

        txtNombreTitular.setText("Nombre del titular");
        txtNombreTitular.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N

        btnContinuar.setBackground(new java.awt.Color(230, 94, 7));
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("Continuar");
        btnContinuar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnContinuar.setHoverColor(new java.awt.Color(255, 255, 255));

        btnVolver.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(0, 0, 0));
        btnVolver.setText("Volver");
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);

        javax.swing.GroupLayout panelRedondeadoLayout = new javax.swing.GroupLayout(panelRedondeado);
        panelRedondeado.setLayout(panelRedondeadoLayout);
        panelRedondeadoLayout.setHorizontalGroup(
            panelRedondeadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeadoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelRedondeadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelRedondeadoLayout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMetodoDePago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroTarjeta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRedondeadoLayout.createSequentialGroup()
                        .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumeroSeguridad, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                    .addComponent(txtNombreTitular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(panelRedondeadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRedondeadoLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(lblSeleccionMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(351, Short.MAX_VALUE)))
        );
        panelRedondeadoLayout.setVerticalGroup(
            panelRedondeadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeadoLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblMetodoDePago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(panelRedondeadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(txtNombreTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelRedondeadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(panelRedondeadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRedondeadoLayout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(lblSeleccionMetodoPago)
                    .addContainerGap(259, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRedondeado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRedondeado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroSeguridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroSeguridadActionPerformed

    private void txtNumeroTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroTarjetaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private itson.org.ghosttracks.utilerias.BotonRedondeado btnContinuar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblMetodoDePago;
    private javax.swing.JLabel lblSeleccionMetodoPago;
    private itson.org.ghosttracks.utilerias.PanelRedondeado panelRedondeado;
    private javax.swing.JPanel pnlPrincipal;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtFechaVencimiento;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtNombreTitular;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtNumeroSeguridad;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtNumeroTarjeta;
    // End of variables declaration//GEN-END:variables
}
